language: python

python:
  # CPython; versions pre-2.7 and 3.0-3.4 have reached EOL
  - "3.6"
  - "3.7-dev" # TODO: change to "3.7" once it is supported by travis-ci

os:
  - linux   # Linux is officially supported and we test the library under
            # many different Python verions (see "python: ..." above)

# - osx     # OSX + Python is not officially supported by Travis CI as of Feb. 2018
            # nevertheless, "nightly" and some "*-dev" versions seem to work, so we
            # include them explicitly below (see "matrix: include: ..." below).
            # They only seem to work with the xcode8.3 image, and not the newer ones.
            # Thus we will leave this in, until it breaks one day, at which point we
            # will probably reomve testing on OSX if it is not supported then.
            # See #385 on Github.

# - windows # Windows is not supported at all by Travis CI as of Feb. 2018

# Linux setup
dist: trusty
sudo: required


install:
  - type pip
  - pip freeze --all
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash test/open_vcan.sh ; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then travis_retry pip install -r doc/doc-requirements.txt; fi
  - pip freeze --all
  - travis_retry pip install --verbose --upgrade .[test,mf4]
  - pip freeze --all

script:
  - type pytest
  - type python
  - python -c 'import pytest; print(pytest)'
  - pytest
  - codecov
  # Build Docs with Sphinx
  # -a Write all files
  # -n nitpicky
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then python -m sphinx -an doc build; fi

